[appenders.console]
kind = "console"

[[appenders.console.filters]]
kind = "threshold"
level = "error"

[appenders.console.encoder]
pattern = "{({l}):1.1} {d(%H:%M:%S.%f):16.16} {([{f}:{L}]):30} {m}\n"



[appenders.file]
kind = "file"
path = "../../../test.log"
append = false

[appenders.file.encoder]
pattern = "{({l}):1.1} {d(%H:%M:%S.%f):16.16} {([{f}:{L}]):30} {m}\n"



[root]
level = "trace"
appenders = ["console", "file"]

# [loggers."crust"]
# level = "debug"
# appenders = ["async_file"]
# additive = false

# [loggers."routing"]
# level = "debug"

# [loggers."safe_vault"]
# level = "debug"
