# {d} - The current time. By default, the ISO 8601 format is used. A custom format may be provided in the syntax accepted by `Tm::sprintf`, enclosed in `{}`s immediately after the specifier: `%d{%Y/%m/%d}`.
# {f} - The source file that the log message came from.
# {l} - The log level.
# {L} - The line that the log message came from.
# {m} - The log message.
# {M} - The module that the log message came from.
# {T} - The name of the thread that the log message came from.
# {t} - The target of the log message.

[appenders.console]
kind = "console"

[[appenders.console.filters]]
kind = "threshold"
level = "error"

[appenders.console.encoder]
pattern = "{({l}):1.1} {d(%H:%M:%S.%f):16.16} {([{f}:{L}]):30} {m}\n"



[appenders.file]
kind = "file"
path = "../../../test.log"
append = false

[appenders.file.encoder]
pattern = "{({l}):1.1} {d(%H:%M:%S.%f):16.16} {([{f}:{L}]):30} {m}\n"



[root]
level = "info"
appenders = ["console", "file"]

[loggers."crust"]
level = "trace"

[loggers."routing"]
level = "trace"

[loggers."routing_stats"]
level = "trace"

[loggers."safe_vault"]
level = "trace"
